apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
data:
  brudi.yaml: |-
{{- if .Values.configmap }}
    # User-supplied configuration:
{{ tpl .Values.configmap . | indent 4 }}
{{- end }}