apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backup.fullname" . }}
  labels:
    {{- include "backup.labels" . | nindent 4 }}
data:
  brudi.yaml: |-
{{ toYaml .Values.brudi.config | indent 4 }}