name: Push stable Brudi-Operator

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install requirements
        run: sudo bash $(pwd)/scripts/requirements.sh

      - name: Log into registry
        run: |
          docker login -u="${{ secrets.DOCKER_USER }}" -p="${{ secrets.DOCKER_PASSWORD }}" quay.io

      - name: Push brudi-operator latest
        env:
          PUSH: "true"
        run: >
          bash $(pwd)/scripts/docker-build-tag.sh "stable" &&
          bash $(pwd)/scripts/docker-build-tag.sh "${GITHUB_REF:10}"